include: package:lints/recommended.yaml
analyzer:
  language:
    strict-casts: true
  errors:
    # There are a number of deprecated members used through this package
    deprecated_member_use_from_same_package: ignore
    unsafe_html: ignore
linter:
  rules:
    - avoid_private_typedef_functions
    - directives_ordering
    - prefer_single_quotes

dart_code_metrics:
  rules:
    - avoid-dynamic
    # - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    # - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    # - newline-before-return
    - no-boolean-literal-compare
    # - no-empty-block
    # - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    # - prefer-moving-to-variable
    # - prefer-match-file-name
    - avoid-collapsible-if
    - avoid-redundant-else
    - avoid-incomplete-copy-with
    - avoid-self-compare
    - avoid-self-assignment
    - avoid-unnecessary-nullable-return-type
    - avoid-unrelated-type-casts
    # - prefer-declaring-const-constructor
